### ISSUE TITLE
Add lint extensions

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#10]
Reading through linters & curious how valuable csslint would be on this project, see https://github.com/lazd/gulp-csslint

**Comment by chasestarr** [comment]
getting the error linked below when implementing this. seems to have an issue understanding new css features like variables

https://stackoverflow.com/questions/22747721/expecting-rbrace-what-is-css-lint-talking-about

**Comment by atav1k** [comment]
I realize it's not a big need anymore because stylelint is more supported & has overlapping features. We might want to look at which stylelint plugins to look into https://stylelint.io/user-guide/plugins/
