### ISSUE TITLE
Add more components

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#25]
Looking at mustard specs, we could include:
- ~~Breadcrumb~~
- Card
- ~~Dropdown~~
- Pagination
- Modal
- Progress
- ~~Stepper~~
- ~~Tooltip~~
- Media

**Comment by atav1k** [comment]
Now added gradient & blend

**Comment by chasestarr** [comment]
do you have a guide for how these look / operate?

**Comment by atav1k** [comment]
@chasestarr I'm porting over some components from https://mustard-ui.com/ like list-step https://github.com/atav1k/fortune/blob/7bc3d1abeab6b13fcb33875322944109d2a73b65/src/list.css#L57-L69

**Comment by atav1k** [comment]
Added breadcrumb, dropdown, stepper & tooltip.
