### ISSUE TITLE
Components lack :root variable

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#31]
Eg. Tabs lack variables that can be uniquely reassigned
https://github.com/atav1k/fortune/blob/e0099beb0774353138870f61f6754ad6ca4b2822/src/tab.css#L8-L9

**Comment by chasestarr** [comment]
this should likely use fallback values: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_variables#Custom_Property_fallback_values

**Comment by atav1k** [comment]
Yess @chasestarr, TIL fallbacks…welcome back

**Comment by atav1k** [comment]
Components now have specs in variable.css
