### ISSUE TITLE
Make the source compartmentalized

### ISSUE THREAD

**Issue by zaydek-old** [atav1k/fortune#38]
You can make your package compartmentalized, sort of similar to Bulma (but this was specified in Sass, not in the URL), in making the source specifiable via a query.

E.g. `fortune.css?all.css` or `fortune.css?helpers.css` so the emphasis is on what do I need versus not need––not give me the whole thing. This is similar to how jQuery had a light version.

This is also brilliant for teaching how to use Fortune in steps; start with some subset of the package and then work up to the whole thing.

**Comment by atav1k** [comment]
There's a placeholder for this in the gulp file which generates the various versions. We've haven't yet decided on which is core vs extensions vs labs (things that require postccss). https://github.com/atav1k/fortune/blob/9cd2efd6263ffc4b2a46dec6dc5d51f9e7d646ed/gulpfile.js#L81-L83

**Comment by chasestarr** [comment]
i believe the package is already small as it is. don't think there is a need to complicate the build process and optimize prematurely
