### ISSUE TITLE
Class names inconsistency

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#39]
Should margins, padding, border, transforms be changed from `p- | m- | b- | t-` => `pad-t- | mar-t- | border-t- | trans-t-|` for beginner readability. This would be a breaking change.

**Comment by chasestarr** [comment]
+1

**Comment by atav1k** [comment]
Single letter classes will replaced in favor of full names or abbreviations where long, eg. `pad-` `width-` `trans` `grad`

**Comment by atav1k** [comment]
Name style conflict between `g-1` using pixels & `gap` as rem variables

**Comment by atav1k** [comment]
So decided to map out all the utility classes prioritizing that vue would make classless components anyhow, and there will be some learning curve. Seemed actually the more intuitive practice, given Javascript affinities, is to write in `CamelCase`!
```
Rad1
BordL1
GradDarken
Blend
Color,BgColor,BordColor
Ht1,ViewHt1,Wid,ViewWid
B,L,R,T
Flex,Grow
GridGap1, GridSpace1
GridCols1, GridRow1
GridColSpan1, GridRowSpan1
Opa1
MarGap1,Mar1,MarT1
PadGap1,Pad1,PadT1
Shad
TransT1
```

**Comment by atav1k** [comment]
Removed `Gap` classes in favor of `isSpace` variant
