### ISSUE TITLE
Remove container from columns

### ISSUE THREAD

**Issue by atav1k** [atav1k/fortune#5]
Current assembly is container > row > col but could be simplified to two layers row > col, see https://github.com/jgthms/bulma/blob/master/sass/grid/columns.sass

**Comment by atav1k** [comment]
@winkerVSbecks do you have a preference using `.cols > .col` over the usual `.container > .row > .col` as there are advantages to both, with `cols` there's lest nesting but you can also just use `.container` without an inner element. _Note: Fortune uses flexbox for columns & has grid utility classes as well._

**Comment by winkerVSbecks** [comment]
I personally prefer `.cols > .col`.  I find that container is generally just responsible for controlling max-width, centring content, etc. and has no impact over the grid. This would make it easy to create a nested grid too.

**Comment by atav1k** [comment]
Need to account for nested cols
```
.cols .cols {
  width: auto;
  margin-left: calc(var(--column-gutter) / -2);
  margin-right: calc(var(--column-gutter) / -2);
}
```
